<a href="https://colab.research.google.com/github/AnmolPipara/GoogleColabPyTorch/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch
tensor1 = torch.rand(7,7)
tensor1

# Create random tensor


tensor([[5.8791e-01, 6.9354e-01, 4.4045e-01, 9.2026e-01, 3.1333e-01, 2.9670e-01,
         2.4054e-01],
        [2.4319e-01, 1.1503e-01, 4.9128e-02, 5.8827e-01, 3.6727e-01, 1.8957e-03,
         8.1143e-01],
        [9.3474e-02, 2.9958e-01, 3.1205e-01, 6.1321e-01, 5.3930e-01, 3.1430e-01,
         6.6311e-01],
        [1.4559e-01, 7.6410e-01, 6.6603e-01, 9.4057e-01, 1.2991e-01, 1.9906e-01,
         9.1055e-01],
        [3.7538e-01, 9.7151e-01, 9.9670e-01, 8.6734e-01, 2.8748e-01, 4.7859e-01,
         4.3696e-04],
        [3.6050e-01, 2.9383e-01, 1.1895e-01, 5.3354e-01, 2.9865e-01, 2.5693e-02,
         2.1227e-01],
        [9.1536e-01, 2.4307e-01, 6.7088e-01, 1.4377e-01, 1.8541e-01, 5.8039e-01,
         4.3552e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.rand(1,7)
torch.mm(tensor1 , tensor2.T)
# Perform matrix multiplication


tensor([[1.3707],
        [0.5527],
        [1.0644],
        [1.4094],
        [1.9205],
        [0.5977],
        [1.4299]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(7,7)

torch.manual_seed(0)

tensor_2 = torch.rand(1,7)

torch.mm(tensor_1 , tensor_2.T),torch.mm(tensor_1 , tensor_2.T).shape


# Matrix multiply tensors


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
import torch

device = "cuda"

torch.cuda.manual_seed(0)

tensor_1 = torch.rand(7, 7, device=device)
tensor_2 = torch.rand(1, 7, device=device)

result = torch.mm(tensor_1, tensor_2.T)
result, result.shape


(tensor([[2.0534],
         [2.3578],
         [1.8793],
         [1.6912],
         [2.5042],
         [2.0659],
         [1.9022]], device='cuda:0'),
 torch.Size([7, 1]))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU

t1 = torch.rand(2,3).to(device)
t2 = torch.rand(2,3).to(device)
t1, t2


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(t1 , t2.T)
res


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
a1 = torch.max(res)
# Find min
a2 =torch.min(res)
a1,a2


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
b1 = torch.argmax(res)

# Find arg min
b2 =torch.argmin(res)
b1,b2

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tt = torch.rand(1,1,1,10)


# Remove single dimensions
sqt = tt.squeeze()

# Print out tensors and their shapes
tt , sqt


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))